"""Unit tests for the config-surface generator (template-repo only)."""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

import jsonschema
import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import gen_config_surface as g


def _marker_pair(region_id: str) -> str:
    """Stand-in text for one spliced region: an empty, already-marked region.

    Mirrors `_generated_region_markers` exactly (not re-imported, since a
    fixture must not depend on the function under test producing its own
    expected input).
    """
    return (
        f"<!-- GENERATED-ENV-TABLE-{region_id}-START — generated by "
        "scripts/gen_config_surface.py; do not edit -->\n"
        f"<!-- GENERATED-ENV-TABLE-{region_id}-END -->\n"
    )


@pytest.fixture
def fake_project(tmp_path):
    """A minimal rendered-project layout the generator can read."""
    (tmp_path / ".copier-answers.yml").write_text(
        "_commit: v2.11.2\n"
        "_src_path: gh:pvliesdonk/fastmcp-server-template\n"
        "project_name: demo-mcp\n"
        "python_module: demo_mcp\n"
        "env_prefix: DEMO_MCP\n"
        "human_name: Demo MCP\n"
        "docker_registry: ghcr.io/demo\n"
        "enable_authorization: false\n",
        encoding="utf-8",
    )
    src = tmp_path / "src" / "demo_mcp"
    src.mkdir(parents=True)
    (src / "__init__.py").write_text("", encoding="utf-8")

    # `write_artifacts` drives off the real (template-root) config-
    # presentation.yml when a fixture project has none of its own, and that
    # file declares two `kind: splice` targets — the OIDC-REQUIRED/
    # OIDC-OPTIONAL regions in both `docs/guides/authentication.md` and
    # `docs/deployment/oidc.md`. Unlike a whole-file artifact, a spliced
    # file must already exist on disk with every one of its marker pairs in
    # place, so every fixture project needs minimal stand-ins here.
    auth_dir = tmp_path / "docs" / "guides"
    auth_dir.mkdir(parents=True)
    (auth_dir / "authentication.md").write_text(
        _marker_pair("OIDC-REQUIRED") + _marker_pair("OIDC-OPTIONAL"),
        encoding="utf-8",
    )
    oidc_dir = tmp_path / "docs" / "deployment"
    oidc_dir.mkdir(parents=True)
    (oidc_dir / "oidc.md").write_text(
        _marker_pair("OIDC-REQUIRED") + _marker_pair("OIDC-OPTIONAL"),
        encoding="utf-8",
    )
    return tmp_path


@pytest.fixture
def template_root():
    """The template repo root — where config-presentation.yml lives."""
    return Path(g.__file__).resolve().parent.parent


@pytest.fixture
def domain_project(fake_project):
    """A project whose ProjectConfig declares one tagged domain field."""
    cfg = fake_project / "src" / "demo_mcp" / "config.py"
    cfg.write_text(
        "from __future__ import annotations\n\n"
        "from dataclasses import dataclass, field\n\n"
        "from fastmcp_pvl_core import ServerConfig, env\n\n\n"
        "@dataclass(frozen=True)\n"
        "class ProjectConfig:\n"
        "    server: ServerConfig = field(default_factory=ServerConfig)\n"
        "    vault_path: str = field(\n"
        '        default="/data/vault",\n'
        '        metadata={"help": "Vault root.", "tags": ("persistence",)},\n'
        "    )\n\n"
        "    @classmethod\n"
        "    def from_env(cls) -> ProjectConfig:\n"
        '        return cls(vault_path=env("DEMO_MCP", "VAULT_PATH") or "/data/vault")\n',
        encoding="utf-8",
    )
    return fake_project


@pytest.fixture
def runnable_project(fake_project, template_root):
    """A fixture project that can run its own copy of the generator.

    `main()`'s `_project_root()` is derived from the generator module's own
    ``__file__``, not from any argument — that is deliberate (a rendered
    project's copy ships byte-identical and must discover its own root at
    runtime), but it also means calling `g.main(...)` in-process from this
    test module would resolve `_project_root()` to *this repo*, not the
    fixture — since `g.__file__` here is the real, tracked
    `scripts/gen_config_surface.py`. Exercising `main()` against a fixture
    therefore requires the fixture to hold its own copy of the script (so
    ``__file__`` resolves inside it) plus its own copies of both
    presentation files, and to run as a genuine subprocess.
    """
    import shutil

    scripts_dir = fake_project / "scripts"
    scripts_dir.mkdir()
    shutil.copy(Path(g.__file__), scripts_dir / "gen_config_surface.py")
    shutil.copy(
        template_root / "config-presentation.yml",
        fake_project / "config-presentation.yml",
    )
    shutil.copy(
        template_root / "config-presentation.domain.yml",
        fake_project / "config-presentation.domain.yml",
    )
    return fake_project


def _run_main(project_root: Path, *args: str) -> subprocess.CompletedProcess[str]:
    """Run *project_root*'s own copy of the generator as a subprocess.

    Uses `sys.executable` (the same interpreter/venv running pytest, which
    already has ``fastmcp-pvl-core``/``pyyaml`` installed) so
    `ensure_core_available` returns immediately instead of trying to
    re-exec under `uv run`.
    """
    script = project_root / "scripts" / "gen_config_surface.py"
    return subprocess.run(
        [sys.executable, str(script), *args],
        cwd=project_root,
        capture_output=True,
        text=True,
        check=False,
    )


class TestLoadAnswers:
    def test_reads_the_copier_answers_file(self, fake_project):
        answers = g.load_answers(fake_project)
        assert answers["env_prefix"] == "DEMO_MCP"
        assert answers["python_module"] == "demo_mcp"

    def test_missing_answers_file_fails_with_a_clear_message(self, tmp_path):
        with pytest.raises(SystemExit, match="copier-answers"):
            g.load_answers(tmp_path)


class TestLoadPresentation:
    def test_substitutes_the_prefix_token(self, template_root):
        pres = g.load_presentation(template_root, "DEMO_MCP")
        names = [v["name"] for v in pres["vars"]]
        assert "DEMO_MCP_HTTP_PATH" in names
        assert not any("{PREFIX}" in n for n in names)

    def test_unprefixed_external_vars_are_left_alone(self, template_root):
        pres = g.load_presentation(template_root, "DEMO_MCP")
        names = [v["name"] for v in pres["vars"]]
        assert "FASTMCP_LOG_LEVEL" in names


class TestCollectVars:
    def test_includes_every_core_field(self, fake_project):
        from fastmcp_pvl_core import server_config_surface

        collected = {
            v.suffix for v in g.collect_vars(fake_project, g.load_answers(fake_project))
        }
        assert {f.suffix for f in server_config_surface()} <= collected

    def test_provenance_order_is_core_then_template_then_external(self, fake_project):
        vars_ = g.collect_vars(fake_project, g.load_answers(fake_project))
        ranks = [
            ("core", "template", "external", "domain").index(v.provenance)
            for v in vars_
        ]
        assert ranks == sorted(ranks)

    def test_core_ordering_matches_declaration_order(self, fake_project):
        from fastmcp_pvl_core import server_config_surface

        core = [
            v.suffix
            for v in g.collect_vars(fake_project, g.load_answers(fake_project))
            if v.provenance == "core"
        ]
        assert core == [f.suffix for f in server_config_surface()]

    def test_authz_vars_absent_when_the_answer_is_false(self, fake_project):
        names = {
            v.name for v in g.collect_vars(fake_project, g.load_answers(fake_project))
        }
        assert "DEMO_MCP_ACL_PATH" not in names

    def test_authz_vars_present_when_the_answer_is_true(self, fake_project):
        p = fake_project / ".copier-answers.yml"
        p.write_text(
            p.read_text(encoding="utf-8").replace(
                "enable_authorization: false", "enable_authorization: true"
            ),
            encoding="utf-8",
        )
        names = {
            v.name for v in g.collect_vars(fake_project, g.load_answers(fake_project))
        }
        assert "DEMO_MCP_ACL_PATH" in names

    def test_prefixed_names_use_the_projects_prefix(self, fake_project):
        names = {
            v.name for v in g.collect_vars(fake_project, g.load_answers(fake_project))
        }
        assert "DEMO_MCP_BASE_URL" in names
        assert not any(n.startswith("SCHOLAR") for n in names)

    def test_every_var_carries_at_least_one_tag(self, fake_project):
        untagged = [
            v.name
            for v in g.collect_vars(fake_project, g.load_answers(fake_project))
            if not v.tags
        ]
        assert untagged == []

    def test_auth_mode_is_collected_despite_being_inferred(self, fake_project):
        """inferred means no wizard control, NOT undocumented — it must still be emitted."""
        vars_ = g.collect_vars(fake_project, g.load_answers(fake_project))
        auth_mode = next(v for v in vars_ if v.suffix == "AUTH_MODE")
        assert auth_mode.inferred is True

    def test_template_provenance_preserves_declaration_order(
        self, fake_project, template_root
    ):
        """A within-rank sort (e.g. by name) would pass the rank-only ordering
        test above but still be wrong — pin declaration order directly."""
        p = fake_project / ".copier-answers.yml"
        p.write_text(
            p.read_text(encoding="utf-8").replace(
                "enable_authorization: false", "enable_authorization: true"
            ),
            encoding="utf-8",
        )
        answers = g.load_answers(fake_project)
        presentation = g.load_presentation(template_root, str(answers["env_prefix"]))
        expected = [
            v["name"] for v in presentation["vars"] if v["provenance"] == "template"
        ]
        collected = [
            v.name
            for v in g.collect_vars(fake_project, answers)
            if v.provenance == "template"
        ]
        assert collected == expected

    def test_missing_env_prefix_fails_loudly(self, fake_project):
        answers = g.load_answers(fake_project)
        del answers["env_prefix"]
        with pytest.raises(SystemExit, match="env_prefix"):
            g.collect_vars(fake_project, answers)

    def test_duplicate_var_name_raises_a_clear_error(self, fake_project, monkeypatch):
        def _fake_load_presentation(project_root, env_prefix):  # noqa: ARG001
            return {
                "vars": [
                    {
                        "name": f"{env_prefix}_TRANSPORT",  # collides with core
                        "provenance": "template",
                        "type_name": "str",
                        "default": None,
                        "help": "duplicate on purpose",
                        "tags": ["server"],
                    }
                ]
            }

        monkeypatch.setattr(g, "load_presentation", _fake_load_presentation)
        with pytest.raises(SystemExit, match="duplicate"):
            g.collect_vars(fake_project, g.load_answers(fake_project))

    def test_collection_is_deterministic_under_hash_randomisation(self, fake_project):
        """Two runs in separate processes must agree, or the render-twice CI diff fails."""
        import os
        import subprocess

        scripts_dir = str(Path(g.__file__).parent)
        project = str(fake_project)
        prog = (
            f"import sys; sys.path.insert(0, {scripts_dir!r});"
            "import gen_config_surface as g;"
            f"a = g.load_answers({project!r});"
            f"print(','.join(v.name for v in g.collect_vars({project!r}, a)))"
        )
        outs = set()
        for seed in ("1", "2", "3"):
            r = subprocess.run(
                [sys.executable, "-c", prog],
                capture_output=True,
                text=True,
                check=True,
                env={**os.environ, "PYTHONHASHSEED": seed},
            )
            outs.add(r.stdout.strip())
        assert len(outs) == 1


class TestEnsureCoreAvailable:
    def test_parses_the_core_floor_from_pyproject(self, tmp_path):
        (tmp_path / "pyproject.toml").write_text(
            'dependencies = [\n  "fastmcp-pvl-core>=4.5.0,<5",\n]\n', encoding="utf-8"
        )
        assert g._core_floor(tmp_path) == "4.5.0"

    def test_parses_the_floor_past_an_extras_marker(self, tmp_path):
        """A KV backend answer renders `fastmcp-pvl-core[redis]>=4.5.0,<5` —
        the extras marker must not defeat the floor match."""
        (tmp_path / "pyproject.toml").write_text(
            'dependencies = [\n  "fastmcp-pvl-core[redis]>=4.5.0,<5",\n]\n',
            encoding="utf-8",
        )
        assert g._core_floor(tmp_path) == "4.5.0"

    def test_parses_a_two_part_floor(self, tmp_path):
        (tmp_path / "pyproject.toml").write_text(
            'dependencies = [\n  "fastmcp-pvl-core>=4.5,<5",\n]\n', encoding="utf-8"
        )
        assert g._core_floor(tmp_path) == "4.5"

    def test_missing_floor_fails_loudly(self, tmp_path):
        (tmp_path / "pyproject.toml").write_text(
            "dependencies = []\n", encoding="utf-8"
        )
        with pytest.raises(SystemExit, match="fastmcp-pvl-core"):
            g._core_floor(tmp_path)

    def test_missing_pyproject_fails_loudly(self, tmp_path):
        with pytest.raises(SystemExit, match=r"pyproject\.toml"):
            g._core_floor(tmp_path)

    def test_matches_the_real_projects_declared_floor(self):
        """Pin against the repo's real pyproject.toml.jinja, not a fixture —
        a fabricated fixture can't notice the declared floor lagging behind
        the fastmcp-pvl-core version this generator actually needs (4.5.0)."""
        real_pyproject = (
            Path(__file__).resolve().parent.parent.parent / "pyproject.toml.jinja"
        )
        floor = g._CORE_FLOOR_RE.search(real_pyproject.read_text(encoding="utf-8"))
        assert floor is not None
        major, minor = (int(part) for part in floor.group(1).split(".")[:2])
        assert (major, minor) >= (4, 5)

    def test_returns_immediately_when_both_deps_are_importable(self, monkeypatch):
        monkeypatch.setattr(g, "_core_importable", lambda: True)
        monkeypatch.setattr(g, "_yaml_importable", lambda: True)

        def _boom(*_args, **_kwargs):
            raise AssertionError("execvpe should not be called")

        monkeypatch.setattr(g.os, "execvpe", _boom)
        # Returns before ever touching project_root, so a nonexistent path is fine.
        g.ensure_core_available(Path("/nonexistent"))

    def test_second_failure_raises_instead_of_looping(self, monkeypatch):
        monkeypatch.setattr(g, "_core_importable", lambda: False)
        monkeypatch.setattr(g, "_yaml_importable", lambda: False)
        monkeypatch.setenv("_GEN_CONFIG_BOOTSTRAPPED", "1")

        def _boom(*_args, **_kwargs):
            raise AssertionError("execvpe should not be called on a repeat failure")

        monkeypatch.setattr(g.os, "execvpe", _boom)
        with pytest.raises(SystemExit, match="still not importable"):
            g.ensure_core_available(Path("/nonexistent"))

    def test_reexec_argv_shape_and_preservation(self, tmp_path, monkeypatch):
        (tmp_path / "pyproject.toml").write_text(
            'dependencies = [\n  "fastmcp-pvl-core>=4.5.0,<5",\n]\n', encoding="utf-8"
        )
        monkeypatch.setattr(g, "_core_importable", lambda: False)
        monkeypatch.setattr(g, "_yaml_importable", lambda: False)
        monkeypatch.delenv("_GEN_CONFIG_BOOTSTRAPPED", raising=False)

        recorded = {}

        def _record_execvpe(file, args, env):
            recorded["file"] = file
            recorded["args"] = args
            recorded["env"] = env

        monkeypatch.setattr(g.os, "execvpe", _record_execvpe)

        g.ensure_core_available(tmp_path, argv=["--check", "--extra-flag"])

        assert recorded["file"] == "uv"
        args = recorded["args"]
        assert "uv" in args
        assert "run" in args
        assert "--no-project" in args
        assert "fastmcp-pvl-core==4.5.0" in args
        assert "pyyaml" in args
        assert args.count("--with") == 2
        # Original script arguments must survive into the re-exec's argv.
        assert "--check" in args
        assert "--extra-flag" in args
        assert recorded["env"]["_GEN_CONFIG_BOOTSTRAPPED"] == "1"

    def test_execvpe_oserror_becomes_a_clear_system_exit(self, tmp_path, monkeypatch):
        (tmp_path / "pyproject.toml").write_text(
            'dependencies = [\n  "fastmcp-pvl-core>=4.5.0,<5",\n]\n', encoding="utf-8"
        )
        monkeypatch.setattr(g, "_core_importable", lambda: False)
        monkeypatch.setattr(g, "_yaml_importable", lambda: False)
        monkeypatch.delenv("_GEN_CONFIG_BOOTSTRAPPED", raising=False)

        def _raise_oserror(*_args, **_kwargs):
            raise OSError("uv not found")

        monkeypatch.setattr(g.os, "execvpe", _raise_oserror)

        with pytest.raises(SystemExit, match="uv"):
            g.ensure_core_available(tmp_path)


class TestRenderEnvFile:
    def _env_text(self, fake_project, template_root, path=".env.example"):
        answers = g.load_answers(fake_project)
        pres = g.load_presentation(template_root, str(answers["env_prefix"]))
        vars_ = g.collect_vars(fake_project, answers)
        return g.render_env_file(pres["files"][path], vars_, answers)

    def test_includes_all_eighteen_core_vars(self, fake_project, template_root):
        """The hand-written .env.example was missing six of them."""
        text = self._env_text(fake_project, template_root)
        for suffix in (
            "APP_DOMAIN",
            "AUTH_MODE",
            "BEARER_DEFAULT_SUBJECT",
            "EVENT_STORE_URL",
            "KV_STORE_URL",
            "OIDC_VERIFY_ACCESS_TOKEN",
        ):
            assert f"DEMO_MCP_{suffix}" in text

    def test_env_example_lines_are_commented_out(self, fake_project, template_root):
        text = self._env_text(fake_project, template_root)
        for line in text.splitlines():
            if "DEMO_MCP_" in line:
                assert line.lstrip().startswith("#")

    def test_packaging_env_lines_are_not_commented(self, fake_project, template_root):
        text = self._env_text(fake_project, template_root, "packaging/env.example")
        assert any(line.startswith("FASTMCP_LOG_LEVEL=") for line in text.splitlines())

    def test_section_titles_appear_in_declared_order(self, fake_project, template_root):
        text = self._env_text(fake_project, template_root)
        positions = [
            text.index(t)
            for t in ("--- Server ---", "--- Authentication ---", "--- Logging ---")
        ]
        assert positions == sorted(positions)

    def test_authz_section_absent_when_answer_false(self, fake_project, template_root):
        assert "Authorization" not in self._env_text(fake_project, template_root)

    def test_help_text_appears_as_a_comment(self, fake_project, template_root):
        text = self._env_text(fake_project, template_root)
        assert "Interface the HTTP server binds to." in text

    def test_render_hygiene_no_trailing_whitespace_single_final_newline(
        self, fake_project, template_root
    ):
        text = self._env_text(fake_project, template_root)
        assert not any(line != line.rstrip() for line in text.splitlines())
        assert text.endswith("\n") and not text.endswith("\n\n")

    def test_output_is_stable_across_calls(self, fake_project, template_root):
        assert self._env_text(fake_project, template_root) == self._env_text(
            fake_project, template_root
        )


class TestDiscoverDomainVars:
    def test_domain_var_is_discovered_with_the_right_name(self, domain_project):
        answers = g.load_answers(domain_project)
        vars_ = g.collect_vars(domain_project, answers)
        assert "DEMO_MCP_VAULT_PATH" in {v.name for v in vars_}

    def test_discovery_does_not_write_bytecode_cache(self, domain_project):
        """Importing the project's own ``config`` module for domain discovery
        must not leave a ``__pycache__`` directory in the rendered project's
        ``src/`` tree. copier's `_tasks` run this generator on every render,
        and template-ci renders the template twice and diffs the results —
        a ``.pyc`` embeds the source file's mtime, so two otherwise-identical
        renders (created at different wall-clock times) would produce
        byte-different cache files and break that diff permanently, even
        though nothing about the generator's own output actually changed.
        """
        answers = g.load_answers(domain_project)
        g.collect_vars(domain_project, answers)
        assert not list((domain_project / "src").rglob("__pycache__"))

    def test_help_and_tags_come_from_field_metadata(self, domain_project):
        answers = g.load_answers(domain_project)
        vars_ = g.collect_vars(domain_project, answers)
        vault = next(v for v in vars_ if v.suffix == "VAULT_PATH")
        assert vault.help == "Vault root."
        assert vault.tags == ("persistence", "domain")
        assert vault.provenance == "domain"

    def test_default_is_extracted_from_the_field(self, domain_project):
        answers = g.load_answers(domain_project)
        vars_ = g.collect_vars(domain_project, answers)
        vault = next(v for v in vars_ if v.suffix == "VAULT_PATH")
        assert vault.default == "/data/vault"

    def test_domain_var_renders_into_env_examples_domain_section(
        self, domain_project, template_root
    ):
        answers = g.load_answers(domain_project)
        pres = g.load_presentation(template_root, str(answers["env_prefix"]))
        vars_ = g.collect_vars(domain_project, answers)
        text = g.render_env_file(pres["files"][".env.example"], vars_, answers)
        assert "--- Domain ---" in text
        assert "DEMO_MCP_VAULT_PATH=/data/vault" in text

    def test_no_stale_sys_modules_leak_across_unrelated_projects(
        self, domain_project, tmp_path_factory
    ):
        """Pins the Critical: importing one project's real ``ProjectConfig``
        must never leak into `sys.modules` and poison a later,
        unrelated call for a *different* project that happens to share the
        same ``python_module`` name — including via a failed import attempt
        that still registers the parent package as a side effect."""
        other_project = tmp_path_factory.mktemp("other_project")
        (other_project / ".copier-answers.yml").write_text(
            "_commit: v2.11.2\n"
            "_src_path: gh:pvliesdonk/fastmcp-server-template\n"
            "project_name: other-mcp\n"
            "python_module: demo_mcp\n"
            "env_prefix: DEMO_MCP\n"
            "human_name: Other MCP\n"
            "docker_registry: ghcr.io/demo\n"
            "enable_authorization: false\n",
            encoding="utf-8",
        )
        other_src = other_project / "src" / "demo_mcp"
        other_src.mkdir(parents=True)
        (other_src / "__init__.py").write_text("", encoding="utf-8")

        before = frozenset(sys.modules)

        domain_answers = g.load_answers(domain_project)
        domain_vars = g.collect_vars(domain_project, domain_answers)
        assert any(v.suffix == "VAULT_PATH" for v in domain_vars)

        other_answers = g.load_answers(other_project)
        other_vars = g.collect_vars(other_project, other_answers)
        assert not any(v.provenance == "domain" for v in other_vars)

        assert frozenset(sys.modules) == before


class TestWriteArtifacts:
    def test_writes_then_reports_clean(self, fake_project):
        g.write_artifacts(fake_project, check=False)
        assert (fake_project / ".env.example").exists()
        assert g.write_artifacts(fake_project, check=True) == []

    def test_check_reports_a_stale_file_without_writing(self, fake_project):
        g.write_artifacts(fake_project, check=False)
        target = fake_project / ".env.example"
        target.write_text("tampered\n", encoding="utf-8")
        assert ".env.example" in g.write_artifacts(fake_project, check=True)
        assert target.read_text(encoding="utf-8") == "tampered\n"

    def test_check_reports_a_missing_file(self, fake_project):
        assert ".env.example" in g.write_artifacts(fake_project, check=True)

    def test_omitting_vars_still_collects_internally(self, fake_project, monkeypatch):
        """The default (no `vars_` argument) must behave exactly as before
        this parameter existed: `write_artifacts` calls `collect_vars` itself
        exactly once."""
        calls: list[object] = []
        real_collect_vars = g.collect_vars

        def _counting_collect_vars(project_root, answers):
            calls.append((project_root, answers))
            return real_collect_vars(project_root, answers)

        monkeypatch.setattr(g, "collect_vars", _counting_collect_vars)

        g.write_artifacts(fake_project, check=False)

        assert len(calls) == 1

    def test_supplying_vars_skips_the_internal_collect_vars_call(
        self, fake_project, monkeypatch
    ):
        """A caller that already collected the surface (e.g. `main()`) must
        be able to pass it through without `write_artifacts` re-collecting —
        `collect_vars` re-imports the project's own `config` module and can
        print a warning to stderr, so a second, internal call would silently
        duplicate that warning."""
        answers = g.load_answers(fake_project)
        vars_ = g.collect_vars(fake_project, answers)

        def _raising_collect_vars(project_root, answers):  # noqa: ARG001
            raise AssertionError(
                "collect_vars must not be called when vars_ is supplied"
            )

        monkeypatch.setattr(g, "collect_vars", _raising_collect_vars)

        written = g.write_artifacts(fake_project, check=False, vars_=vars_)

        assert ".env.example" in written


class TestUnplacedVarGuard:
    """C1: a var whose tags match no env-file section used to vanish from
    every generated artifact with exit 0 and no warning. `write_artifacts`
    must now catch that before writing anything."""

    def _with_extra_template_var(self, extra_var):
        real_load_presentation = g.load_presentation

        def _fake_load_presentation(project_root, env_prefix):
            pres = dict(real_load_presentation(project_root, env_prefix))
            pres["vars"] = [*pres.get("vars", ()), extra_var(env_prefix)]
            return pres

        return _fake_load_presentation

    def test_var_with_unmatched_tag_raises(self, fake_project, monkeypatch):
        monkeypatch.setattr(
            g,
            "load_presentation",
            self._with_extra_template_var(
                lambda env_prefix: {
                    "name": f"{env_prefix}_MYSTERY",
                    "provenance": "template",
                    "type_name": "str",
                    "default": None,
                    "help": "Matches no section tag.",
                    "tags": ["no_such_tag"],
                }
            ),
        )
        with pytest.raises(SystemExit, match="MYSTERY"):
            g.write_artifacts(fake_project, check=False)

    def test_var_with_no_tags_at_all_raises(self, fake_project, monkeypatch):
        """Omitting `tags:` entirely is the likelier author mistake than a typo."""
        monkeypatch.setattr(
            g,
            "load_presentation",
            self._with_extra_template_var(
                lambda env_prefix: {
                    "name": f"{env_prefix}_MYSTERY",
                    "provenance": "template",
                    "type_name": "str",
                    "default": None,
                    "help": "No tags key at all.",
                }
            ),
        )
        with pytest.raises(SystemExit, match="MYSTERY"):
            g.write_artifacts(fake_project, check=False)

    def test_error_names_the_known_section_tags(self, fake_project, monkeypatch):
        monkeypatch.setattr(
            g,
            "load_presentation",
            self._with_extra_template_var(
                lambda env_prefix: {
                    "name": f"{env_prefix}_MYSTERY",
                    "provenance": "template",
                    "type_name": "str",
                    "default": None,
                    "help": "Matches no section tag.",
                    "tags": ["no_such_tag"],
                }
            ),
        )
        with pytest.raises(SystemExit, match="server"):
            g.write_artifacts(fake_project, check=False)


class TestDomainYamlTagging:
    """C1: `config-presentation.domain.yml` vars must get the same implicit
    `domain` tag `_discover_domain_vars` adds, so a var declared there always
    matches the Domain section regardless of its own declared tags."""

    def test_domain_yaml_var_gets_domain_tag_and_lands_in_env_example(
        self, fake_project, template_root, monkeypatch
    ):
        def _fake_domain_presentation(presentation_root, env_prefix):  # noqa: ARG001
            return {
                "vars": [
                    {
                        "name": f"{env_prefix}_VAULT_PATH",
                        "type_name": "Path",
                        "default": None,
                        "help": "Filesystem root of the vault.",
                        "tags": ["storage"],
                    }
                ]
            }

        monkeypatch.setattr(g, "_load_domain_presentation", _fake_domain_presentation)
        answers = g.load_answers(fake_project)
        vars_ = g.collect_vars(fake_project, answers)
        var = next(v for v in vars_ if v.suffix == "VAULT_PATH")
        assert var.tags == ("storage", "domain")

        pres = g.load_presentation(template_root, str(answers["env_prefix"]))
        text = g.render_env_file(pres["files"][".env.example"], vars_, answers)
        assert "DEMO_MCP_VAULT_PATH" in text

    def test_domain_yaml_var_with_no_tags_still_lands_via_the_domain_tag(
        self, fake_project, template_root, monkeypatch
    ):
        def _fake_domain_presentation(presentation_root, env_prefix):  # noqa: ARG001
            return {
                "vars": [
                    {
                        "name": f"{env_prefix}_UNTAGGED",
                        "type_name": "str",
                        "default": None,
                        "help": "No tags declared at all.",
                    }
                ]
            }

        monkeypatch.setattr(g, "_load_domain_presentation", _fake_domain_presentation)
        answers = g.load_answers(fake_project)
        vars_ = g.collect_vars(fake_project, answers)
        var = next(v for v in vars_ if v.suffix == "UNTAGGED")
        assert var.tags == ("domain",)

        pres = g.load_presentation(template_root, str(answers["env_prefix"]))
        text = g.render_env_file(pres["files"][".env.example"], vars_, answers)
        assert "DEMO_MCP_UNTAGGED" in text


class TestImportProjectConfigWarnings:
    """I3: `_import_project_config` used to swallow every exception silently,
    so a broken `config.py` (a `SyntaxError`, a missing third-party import)
    made every domain var vanish from the generated artifacts with no
    diagnostic at all — most realistically during copier-update's bootstrap
    re-exec, which has none of the project's own dependencies installed."""

    def _import(self, project_root, python_module):
        """Run `_import_project_config` and clean up any `sys.modules` entry
        it leaves behind — mirrors `_discover_domain_vars`'s own cleanup, so
        this test can't leak a stale module into a later test that happens
        to share the same `python_module` name."""
        before = frozenset(sys.modules)
        try:
            return g._import_project_config(project_root, python_module)
        finally:
            for name in set(sys.modules) - before:
                del sys.modules[name]

    def test_missing_config_module_is_silent(self, fake_project, capsys):
        """`fake_project` has no `config.py` at all — a legitimate, silent
        'nothing to discover', not a warning-worthy failure."""
        result = self._import(fake_project, "demo_mcp")
        assert result is None
        assert capsys.readouterr().err == ""

    def test_syntax_error_in_config_warns_and_returns_none(self, fake_project, capsys):
        cfg = fake_project / "src" / "demo_mcp" / "config.py"
        cfg.write_text("def broken(:\n    pass\n", encoding="utf-8")

        result = self._import(fake_project, "demo_mcp")

        assert result is None
        err = capsys.readouterr().err
        assert "WARNING" in err
        assert "demo_mcp.config" in err
        assert "SyntaxError" in err

    def test_third_party_import_error_in_config_warns_and_returns_none(
        self, fake_project, capsys
    ):
        """The realistic copier-update trigger: `_tasks` bootstraps into an
        environment with none of the project's own dependencies, so any
        third-party import in `config.py` raises here."""
        cfg = fake_project / "src" / "demo_mcp" / "config.py"
        cfg.write_text("import no_such_third_party_dependency_xyz\n", encoding="utf-8")

        result = self._import(fake_project, "demo_mcp")

        assert result is None
        err = capsys.readouterr().err
        assert "WARNING" in err
        assert "demo_mcp.config" in err
        assert "ModuleNotFoundError" in err


class TestRenderWizardSpec:
    def _spec(self, fake_project, template_root):
        import json

        answers = g.load_answers(fake_project)
        pres = g.load_presentation(template_root, str(answers["env_prefix"]))
        vars_ = g.collect_vars(fake_project, answers)
        return json.loads(g.render_wizard_spec(pres, vars_, answers))

    def test_meta_comes_from_copier_answers(self, fake_project, template_root):
        meta = self._spec(fake_project, template_root)["meta"]
        assert meta["projectName"] == "demo-mcp"
        assert meta["envPrefix"] == "DEMO_MCP"
        assert meta["dockerImage"] == "ghcr.io/demo/demo-mcp:latest"

    def test_secret_keys_come_from_the_secret_hint(self, fake_project, template_root):
        assert set(self._spec(fake_project, template_root)["secretKeys"]) == {
            "DEMO_MCP_BEARER_TOKEN",
            "DEMO_MCP_OIDC_CLIENT_SECRET",
            "DEMO_MCP_OIDC_JWT_SIGNING_KEY",
        }

    def test_routing_questions_come_first(self, fake_project, template_root):
        ids = [q["id"] for q in self._spec(fake_project, template_root)["questions"]]
        assert ids[:1] == ["deployment"]
        assert "auth" in ids

    def test_inferred_vars_get_no_question(self, fake_project, template_root):
        """AUTH_MODE is documented in env files but offered no wizard control."""
        spec = self._spec(fake_project, template_root)
        emitted = {q.get("var") for q in spec["questions"]}
        assert "DEMO_MCP_AUTH_MODE" not in emitted

    def test_transport_is_emitted_by_the_routing_select_not_a_question(
        self, fake_project, template_root
    ):
        spec = self._spec(fake_project, template_root)
        assert "DEMO_MCP_TRANSPORT" not in {q.get("var") for q in spec["questions"]}
        emits = [
            k
            for q in spec["questions"]
            for o in q.get("options", [])
            for k in (o.get("emit") or {})
        ]
        assert "DEMO_MCP_TRANSPORT" in emits

    def test_group_hint_becomes_advanced_group(self, fake_project, template_root):
        q = next(
            q
            for q in self._spec(fake_project, template_root)["questions"]
            if q.get("var") == "DEMO_MCP_HOST"
        )
        assert q["advancedGroup"] == "Server"

    def test_when_oidc_becomes_a_two_dimensional_show_if(
        self, fake_project, template_root
    ):
        q = next(
            q
            for q in self._spec(fake_project, template_root)["questions"]
            if q.get("var") == "DEMO_MCP_OIDC_CLIENT_ID"
        )
        assert q["showIf"] == {"deployment": ["server"], "auth": ["oidc", "both"]}

    def test_guard_message_no_longer_claims_an_ephemeral_key(
        self, fake_project, template_root
    ):
        """#260: the old wording was false — the key is derived deterministically."""
        text = " ".join(
            gd["message"] for gd in self._spec(fake_project, template_root)["guards"]
        )
        assert "ephemeral" not in text.lower()

    def test_output_ends_with_exactly_one_newline(self, fake_project, template_root):
        answers = g.load_answers(fake_project)
        pres = g.load_presentation(template_root, str(answers["env_prefix"]))
        text = g.render_wizard_spec(
            pres, g.collect_vars(fake_project, answers), answers
        )
        assert text.endswith("\n") and not text.endswith("\n\n")


class TestExampleEnvFiles:
    def test_bearer_example_carries_only_bearer_tagged_vars(self, fake_project):
        g.write_artifacts(fake_project, check=False)
        text = (fake_project / "examples" / "bearer-auth.env").read_text(
            encoding="utf-8"
        )
        assert "DEMO_MCP_BEARER_TOKEN" in text
        assert "DEMO_MCP_OIDC_CLIENT_ID" not in text

    def test_no_placeholder_read_only_var_survives(self, fake_project):
        """The hand-written examples shipped READ_ONLY, which exists nowhere."""
        g.write_artifacts(fake_project, check=False)
        for name in ("bearer-auth.env", "oidc.env"):
            text = (fake_project / "examples" / name).read_text(encoding="utf-8")
            assert "READ_ONLY" not in text

    def test_bearer_example_excludes_the_tokens_file_var(self, fake_project):
        """#260 fix-round: shipping both BEARER_TOKEN and BEARER_TOKENS_FILE
        makes core prefer the (non-existent) tokens file and refuse to start."""
        g.write_artifacts(fake_project, check=False)
        text = (fake_project / "examples" / "bearer-auth.env").read_text(
            encoding="utf-8"
        )
        assert "BEARER_TOKENS_FILE" not in text

    def test_oidc_example_has_no_bare_value_lines(self, fake_project):
        """#260 fix-round: an unset OIDC var silently yields auth_mode=None.
        Every var whose real default is null (so it would otherwise render
        blank) must render a non-empty value in this file. `REQUIRED_SCOPES`
        is deliberately excluded: its real default is `()`, an empty-but-
        non-null "no restriction" value that always wins over an example —
        rendering blank there is correct, not the #260 defect."""
        g.write_artifacts(fake_project, check=False)
        text = (fake_project / "examples" / "oidc.env").read_text(encoding="utf-8")
        must_be_set = (
            "DEMO_MCP_BASE_URL",
            "DEMO_MCP_OIDC_CONFIG_URL",
            "DEMO_MCP_OIDC_CLIENT_ID",
            "DEMO_MCP_OIDC_CLIENT_SECRET",
            "DEMO_MCP_OIDC_JWT_SIGNING_KEY",
            "DEMO_MCP_OIDC_AUDIENCE",
        )
        lines_by_var = {
            line.split("=", 1)[0]: line
            for line in text.splitlines()
            if not line.lstrip().startswith("#")
        }
        for name in must_be_set:
            assert name in lines_by_var, f"{name} missing from oidc.env"
            assert not lines_by_var[name].endswith("="), (
                f"bare value line: {lines_by_var[name]!r}"
            )


class TestGeneratedSpecMatchesShippedSchema:
    def test_generated_spec_validates(self, fake_project, template_root):
        schema_path = (
            template_root
            / "docs"
            / "javascripts"
            / "config-wizard"
            / "wizard-spec-schema.json"
        )
        schema = json.loads(schema_path.read_text(encoding="utf-8"))
        answers = g.load_answers(fake_project)
        pres = g.load_presentation(template_root, str(answers["env_prefix"]))
        spec = json.loads(
            g.render_wizard_spec(pres, g.collect_vars(fake_project, answers), answers)
        )
        jsonschema.validate(instance=spec, schema=schema)


class TestWizardSpecProminence:
    """The gap that let Group-1 findings through: nothing asserted which
    questions are primary (no `showIf`, no `advancedGroup`) — a var with an
    unrecognised or missing hint silently became one."""

    def test_only_deployment_is_primary(self, fake_project, template_root):
        answers = g.load_answers(fake_project)
        pres = g.load_presentation(template_root, str(answers["env_prefix"]))
        spec = json.loads(
            g.render_wizard_spec(pres, g.collect_vars(fake_project, answers), answers)
        )
        primary = {
            q["id"]
            for q in spec["questions"]
            if not q.get("showIf") and not q.get("advancedGroup")
        }
        assert primary == {"deployment"}


class TestWizardControlNone:
    def test_control_none_var_gets_no_question_but_stays_in_env_example(
        self, fake_project, template_root
    ):
        answers = g.load_answers(fake_project)
        pres = g.load_presentation(template_root, str(answers["env_prefix"]))
        vars_ = g.collect_vars(fake_project, answers)
        spec = json.loads(g.render_wizard_spec(pres, vars_, answers))
        assert "DEMO_MCP_DEBUG_PORT" not in {q.get("var") for q in spec["questions"]}

        g.write_artifacts(fake_project, check=False)
        env_text = (fake_project / ".env.example").read_text(encoding="utf-8")
        assert "DEMO_MCP_DEBUG_PORT" in env_text


class TestWizardHintValidation:
    def _var(self, **wizard):
        return g.Var(
            name="DEMO_MCP_WIDGET",
            suffix="WIDGET",
            provenance="domain",
            type_name="str",
            default=None,
            help="A widget.",
            tags=("domain",),
            inferred=False,
            wizard=wizard,
        )

    def test_unknown_hint_key_raises_naming_the_var(self):
        with pytest.raises(SystemExit, match="DEMO_MCP_WIDGET"):
            g._validate_wizard_hint(self._var(bogus_key="x"))

    def test_unknown_when_token_raises_naming_the_var(self):
        with pytest.raises(SystemExit, match="DEMO_MCP_WIDGET"):
            g._validate_wizard_hint(self._var(when="servr"))

    def test_unknown_control_value_raises_naming_the_var(self):
        with pytest.raises(SystemExit, match="DEMO_MCP_WIDGET"):
            g._validate_wizard_hint(self._var(control="delete"))


class TestSecretKeysSubsetOfQuestions:
    def test_secret_keys_are_a_subset_of_emitted_question_vars(
        self, fake_project, template_root
    ):
        answers = g.load_answers(fake_project)
        pres = g.load_presentation(template_root, str(answers["env_prefix"]))
        spec = json.loads(
            g.render_wizard_spec(pres, g.collect_vars(fake_project, answers), answers)
        )
        question_vars = {q["var"] for q in spec["questions"] if "var" in q}
        assert set(spec["secretKeys"]) <= question_vars


class TestQuestionIdCollision:
    def test_colliding_question_id_raises(self, fake_project, template_root):
        answers = g.load_answers(fake_project)
        pres = g.load_presentation(template_root, str(answers["env_prefix"]))
        vars_ = g.collect_vars(fake_project, answers)
        colliding = g.Var(
            name="DEMO_MCP_AUTH",
            suffix="AUTH",
            provenance="domain",
            type_name="str",
            default=None,
            help="Collides with the routing question id.",
            tags=("domain",),
            inferred=False,
            wizard={},
        )
        with pytest.raises(SystemExit, match="auth"):
            g.render_wizard_spec(pres, (*vars_, colliding), answers)


class TestUnknownFileKind:
    def test_unknown_kind_in_files_raises(self, fake_project, monkeypatch):
        def _fake_load_presentation(project_root, env_prefix):  # noqa: ARG001
            return {
                "files": {
                    "mystery.txt": {"kind": "mystery"},
                },
                "wizard_routing": [],
                "wizard_guards": [],
            }

        monkeypatch.setattr(g, "load_presentation", _fake_load_presentation)
        with pytest.raises(SystemExit, match="mystery"):
            g.write_artifacts(fake_project, check=False)


class TestWizardLabelOverrides:
    def test_label_comes_from_override_map_where_declared(
        self, fake_project, template_root
    ):
        answers = g.load_answers(fake_project)
        pres = g.load_presentation(template_root, str(answers["env_prefix"]))
        spec = json.loads(
            g.render_wizard_spec(pres, g.collect_vars(fake_project, answers), answers)
        )
        q = next(
            q for q in spec["questions"] if q.get("var") == "DEMO_MCP_OIDC_CLIENT_ID"
        )
        assert q["label"] == "OIDC client ID"

    def test_label_falls_back_to_the_mechanical_derivation_otherwise(
        self, fake_project, template_root
    ):
        answers = g.load_answers(fake_project)
        pres = g.load_presentation(template_root, str(answers["env_prefix"]))
        spec = json.loads(
            g.render_wizard_spec(pres, g.collect_vars(fake_project, answers), answers)
        )
        q = next(q for q in spec["questions"] if q.get("var") == "DEMO_MCP_SERVER_NAME")
        assert q["label"] == "Server Name"


class TestMain:
    def test_main_writes_both_artifacts_and_returns_zero(self, runnable_project):
        result = _run_main(runnable_project)
        assert result.returncode == 0, result.stderr
        assert (runnable_project / ".env.example").exists()
        assert (runnable_project / "packaging" / "env.example").exists()

    def test_check_returns_one_when_artifacts_are_missing_and_writes_nothing(
        self, runnable_project
    ):
        result = _run_main(runnable_project, "--check")
        assert result.returncode == 1
        assert not (runnable_project / ".env.example").exists()
        assert not (runnable_project / "packaging" / "env.example").exists()

    def test_check_returns_zero_after_a_successful_write(self, runnable_project):
        write_result = _run_main(runnable_project)
        assert write_result.returncode == 0, write_result.stderr

        check_result = _run_main(runnable_project, "--check")
        assert check_result.returncode == 0

    def test_check_returns_one_when_tampered_and_leaves_it_untouched(
        self, runnable_project
    ):
        write_result = _run_main(runnable_project)
        assert write_result.returncode == 0, write_result.stderr

        target = runnable_project / ".env.example"
        target.write_text("tampered\n", encoding="utf-8")

        check_result = _run_main(runnable_project, "--check")
        assert check_result.returncode == 1
        assert target.read_text(encoding="utf-8") == "tampered\n"

    def test_broken_config_warns_exactly_once_per_invocation(self, runnable_project):
        """C-double-collect: `main()` used to call `collect_vars` twice per
        invocation (once directly, once again inside `write_artifacts`), and
        `collect_vars` imports the project's own `config` module as part of
        domain discovery. A project whose `config.py` fails to import (e.g.
        it references a third-party package that is absent — exactly what
        happens on the copier-update bootstrap path, which runs under
        `uv run --no-project` with none of the project's own dependencies
        installed) must print exactly one `WARNING:` line to stderr for one
        `main()` invocation, not two identical ones for the same problem."""
        cfg = runnable_project / "src" / "demo_mcp" / "config.py"
        cfg.write_text("import nonexistent_third_party_pkg_xyz\n", encoding="utf-8")

        result = _run_main(runnable_project)

        assert result.returncode == 0, result.stderr
        warning_lines = [
            line for line in result.stderr.splitlines() if line.startswith("WARNING")
        ]
        assert len(warning_lines) == 1, result.stderr


class TestRenderMdTable:
    def test_two_column_shape(self, fake_project, template_root):  # noqa: ARG002
        answers = g.load_answers(fake_project)
        vars_ = [v for v in g.collect_vars(fake_project, answers) if "oidc" in v.tags]
        table = g.render_md_table(vars_, ["variable", "description"])
        lines = table.splitlines()
        assert lines[0] == "| Variable | Description |"
        assert lines[1] == "|---|---|"
        assert all(line.count("|") == 3 for line in lines[2:])

    def test_three_column_shape_includes_default(
        self,
        fake_project,
        template_root,  # noqa: ARG002
    ):
        answers = g.load_answers(fake_project)
        vars_ = [v for v in g.collect_vars(fake_project, answers) if "readme" in v.tags]
        table = g.render_md_table(vars_, ["variable", "default", "description"])
        assert table.splitlines()[0] == "| Variable | Default | Description |"

    def test_required_column_is_derived_from_a_null_default(self, fake_project):
        answers = g.load_answers(fake_project)
        vars_ = g.collect_vars(fake_project, answers)
        base_url = next(v for v in vars_ if v.suffix == "BASE_URL")
        host = next(v for v in vars_ if v.suffix == "HOST")
        req = g.render_md_table([base_url, host], ["variable", "required"])
        rows = {
            ln.split("|")[1].strip(): ln.split("|")[2].strip()
            for ln in req.splitlines()[2:]
        }
        assert rows[f"`{base_url.name}`"] == "**Yes**"
        assert rows[f"`{host.name}`"] == "No"

    def test_pipe_in_a_value_is_escaped(self):
        """An unescaped pipe would split the row and corrupt the rendered table."""
        v = g.Var(
            name="X_A",
            suffix="A",
            provenance="template",
            type_name="str",
            default="a|b",
            help="has | pipe",
            tags=("t",),
            inferred=False,
            wizard={},
        )
        table = g.render_md_table([v], ["variable", "default", "description"])
        row = table.splitlines()[2]
        assert r"\|" in row
        # A 3-column row has exactly 4 unescaped pipes: leading, two separators, trailing.
        assert len(re.findall(r"(?<!\\)\|", row)) == 4

    def test_no_trailing_whitespace_and_no_final_newline(self, fake_project):
        answers = g.load_answers(fake_project)
        table = g.render_md_table(
            list(g.collect_vars(fake_project, answers))[:3], ["variable", "description"]
        )
        assert not table.endswith("\n")
        assert all(line == line.rstrip() for line in table.splitlines())


class TestSpliceRegion:
    _DOC = (
        "intro\n"
        "<!-- GENERATED-ENV-TABLE-AUTH-START — generated by "
        "scripts/gen_config_surface.py; do not edit -->\n"
        "old content\n"
        "<!-- GENERATED-ENV-TABLE-AUTH-END -->\n"
        "outro\n"
    )

    def test_replaces_only_the_region_body(self):
        out = g.splice_region(self._DOC, "AUTH", "NEW", source="docs/x.md")
        assert "old content" not in out
        assert "NEW" in out
        assert out.startswith("intro\n")
        assert out.endswith("outro\n")

    def test_markers_survive(self):
        out = g.splice_region(self._DOC, "AUTH", "NEW", source="docs/x.md")
        assert "GENERATED-ENV-TABLE-AUTH-START" in out
        assert "GENERATED-ENV-TABLE-AUTH-END" in out

    def test_is_idempotent(self):
        once = g.splice_region(self._DOC, "AUTH", "NEW", source="docs/x.md")
        assert g.splice_region(once, "AUTH", "NEW", source="docs/x.md") == once

    def test_missing_start_marker_raises(self):
        with pytest.raises(SystemExit, match="AUTH"):
            g.splice_region("no markers here\n", "AUTH", "NEW", source="docs/x.md")

    def test_missing_end_marker_raises(self):
        broken = self._DOC.replace("<!-- GENERATED-ENV-TABLE-AUTH-END -->\n", "")
        with pytest.raises(SystemExit, match="AUTH"):
            g.splice_region(broken, "AUTH", "NEW", source="docs/x.md")

    def test_duplicated_region_raises(self):
        with pytest.raises(SystemExit, match="AUTH"):
            g.splice_region(self._DOC + self._DOC, "AUTH", "NEW", source="docs/x.md")

    def test_end_before_start_raises(self):
        swapped = (
            "<!-- GENERATED-ENV-TABLE-AUTH-END -->\n"
            "<!-- GENERATED-ENV-TABLE-AUTH-START — generated by "
            "scripts/gen_config_surface.py; do not edit -->\n"
        )
        with pytest.raises(SystemExit, match="AUTH"):
            g.splice_region(swapped, "AUTH", "NEW", source="docs/x.md")

    def test_error_names_the_source_file(self):
        """A region-id-only message can't tell an operator which file broke
        when two files declare the same region id — the message must name
        *source* too."""
        broken = self._DOC.replace("<!-- GENERATED-ENV-TABLE-AUTH-END -->\n", "")
        with pytest.raises(SystemExit, match=r"docs/deployment/oidc\.md"):
            g.splice_region(broken, "AUTH", "NEW", source="docs/deployment/oidc.md")

    def test_same_region_id_broken_in_two_files_yields_distinct_messages(self):
        """The concrete ambiguity this fixes: `docs/deployment/oidc.md` and
        `docs/guides/authentication.md` both declare `OIDC-REQUIRED`/
        `OIDC-OPTIONAL`. Breaking the same-id marker in each must not raise
        byte-identical text — an operator hitting the marker-drop hazard
        needs the message to say which file to fix."""
        broken = self._DOC.replace("<!-- GENERATED-ENV-TABLE-AUTH-END -->\n", "")

        with pytest.raises(SystemExit) as exc_oidc:
            g.splice_region(broken, "AUTH", "NEW", source="docs/deployment/oidc.md")
        with pytest.raises(SystemExit) as exc_auth:
            g.splice_region(
                broken, "AUTH", "NEW", source="docs/guides/authentication.md"
            )

        message_oidc = str(exc_oidc.value)
        message_auth = str(exc_auth.value)
        assert message_oidc != message_auth
        assert "docs/deployment/oidc.md" in message_oidc
        assert "docs/guides/authentication.md" in message_auth


class TestSelectRegionVars:
    """Fix round 1: the `required:` region filter. A var is required iff its
    resolved default is `None` — the same derivation `_md_required_cell`
    already uses for the `required` table column."""

    def test_required_true_keeps_only_null_default_vars(self, fake_project):
        answers = g.load_answers(fake_project)
        vars_ = g.collect_vars(fake_project, answers)
        selected = g._select_region_vars(vars_, {"tags": ["oidc"], "required": True})
        assert selected
        assert all(v.default is None for v in selected)

    def test_required_false_keeps_only_non_null_default_vars(self, fake_project):
        answers = g.load_answers(fake_project)
        vars_ = g.collect_vars(fake_project, answers)
        selected = g._select_region_vars(vars_, {"tags": ["oidc"], "required": False})
        assert selected
        assert all(v.default is not None for v in selected)

    def test_required_true_and_false_are_disjoint_and_union_to_the_unfiltered_set(
        self, fake_project
    ):
        answers = g.load_answers(fake_project)
        vars_ = g.collect_vars(fake_project, answers)
        unfiltered = {v.name for v in g._select_region_vars(vars_, {"tags": ["oidc"]})}
        required = {
            v.name
            for v in g._select_region_vars(vars_, {"tags": ["oidc"], "required": True})
        }
        optional = {
            v.name
            for v in g._select_region_vars(vars_, {"tags": ["oidc"], "required": False})
        }
        assert required & optional == set()
        assert required | optional == unfiltered

    def test_omitted_required_key_still_returns_every_tag_matched_var(
        self, fake_project
    ):
        """Preserves the pre-filter behaviour: no `required:` key at all
        means no filtering, not "filter to nothing"."""
        answers = g.load_answers(fake_project)
        vars_ = g.collect_vars(fake_project, answers)
        by_hand = [v for v in vars_ if {"oidc"} & set(v.tags)]
        selected = g._select_region_vars(vars_, {"tags": ["oidc"]})
        assert [v.name for v in selected] == [v.name for v in by_hand]

    def test_oidc_region_excludes_bearer_only_vars(self, fake_project):
        """The selector is `tags: [oidc]`, not
        `tags: [auth]`, so a bearer-only var never lands in an OIDC table."""
        answers = g.load_answers(fake_project)
        vars_ = g.collect_vars(fake_project, answers)
        selected = g._select_region_vars(vars_, {"tags": ["oidc"], "required": True})
        assert "DEMO_MCP_BEARER_TOKEN" not in {v.name for v in selected}


class TestSelectRegionVarsWithRequiredNames:
    """The region-level view of `config-presentation.yml`'s real
    `required_vars:` list — the `OIDC-REQUIRED`/`OIDC-OPTIONAL` split as it
    actually happens once `required_names` is threaded through, not the
    provenance-only fallback `TestSelectRegionVars` above exercises."""

    def _oidc_names(self, fake_project, template_root, required):
        answers = g.load_answers(fake_project)
        pres = g.load_presentation(template_root, str(answers["env_prefix"]))
        required_names = frozenset(pres["required_vars"])
        vars_ = g.collect_vars(fake_project, answers)
        selected = g._select_region_vars(
            vars_, {"tags": ["oidc"], "required": required}, required_names
        )
        return {v.name for v in selected}

    def test_required_true_is_exactly_the_four_prerequisites(
        self, fake_project, template_root
    ):
        names = self._oidc_names(fake_project, template_root, True)
        assert names == {
            "DEMO_MCP_BASE_URL",
            "DEMO_MCP_OIDC_CONFIG_URL",
            "DEMO_MCP_OIDC_CLIENT_ID",
            "DEMO_MCP_OIDC_CLIENT_SECRET",
        }

    def test_required_false_is_the_remaining_oidc_tagged_vars(
        self, fake_project, template_root
    ):
        names = self._oidc_names(fake_project, template_root, False)
        assert names == {
            "DEMO_MCP_OIDC_AUDIENCE",
            "DEMO_MCP_OIDC_JWT_SIGNING_KEY",
            "DEMO_MCP_OIDC_REQUIRED_SCOPES",
            "DEMO_MCP_OIDC_VERIFY_ACCESS_TOKEN",
        }

    def test_required_and_optional_are_disjoint_and_union_to_the_unfiltered_oidc_set(
        self, fake_project, template_root
    ):
        answers = g.load_answers(fake_project)
        vars_ = g.collect_vars(fake_project, answers)
        unfiltered = {v.name for v in g._select_region_vars(vars_, {"tags": ["oidc"]})}
        required = self._oidc_names(fake_project, template_root, True)
        optional = self._oidc_names(fake_project, template_root, False)
        assert required & optional == set()
        assert required | optional == unfiltered


class TestRenderSpliceFileMultiRegion:
    def test_two_regions_splice_in_one_pass_and_stay_idempotent(self, tmp_path):
        target = tmp_path / "doc.md"
        target.write_text(
            "# Doc\n\n"
            "## Required\n\n"
            "<!-- GENERATED-ENV-TABLE-A-START — generated by "
            "scripts/gen_config_surface.py; do not edit -->\n"
            "<!-- GENERATED-ENV-TABLE-A-END -->\n\n"
            "## Optional\n\n"
            "<!-- GENERATED-ENV-TABLE-B-START — generated by "
            "scripts/gen_config_surface.py; do not edit -->\n"
            "<!-- GENERATED-ENV-TABLE-B-END -->\n",
            encoding="utf-8",
        )
        v_required = g.Var(
            name="X_REQ",
            suffix="REQ",
            provenance="template",
            type_name="str",
            default=None,
            help="Required one.",
            tags=("t",),
            inferred=False,
            wizard={},
        )
        v_optional = g.Var(
            name="X_OPT",
            suffix="OPT",
            provenance="template",
            type_name="str",
            default="v",
            help="Optional one.",
            tags=("t",),
            inferred=False,
            wizard={},
        )
        file_spec = {
            "regions": [
                {"id": "A", "tags": ["t"], "required": True, "columns": ["variable"]},
                {"id": "B", "tags": ["t"], "required": False, "columns": ["variable"]},
            ]
        }
        once = g.render_splice_file(
            tmp_path, "doc.md", file_spec, [v_required, v_optional]
        )
        region_a = once.split("GENERATED-ENV-TABLE-A-START")[1].split(
            "GENERATED-ENV-TABLE-A-END"
        )[0]
        region_b = once.split("GENERATED-ENV-TABLE-B-START")[1].split(
            "GENERATED-ENV-TABLE-B-END"
        )[0]
        assert "X_REQ" in region_a and "X_OPT" not in region_a
        assert "X_OPT" in region_b and "X_REQ" not in region_b

        target.write_text(once, encoding="utf-8")
        twice = g.render_splice_file(
            tmp_path, "doc.md", file_spec, [v_required, v_optional]
        )
        assert twice == once


class TestCleanHelpForMarkdownTable:
    """Fix round 4: a spliced table cell lands in `docs/`, which every
    downstream lints with Vale at `MinAlertLevel = error`. Core's field
    metadata (already published in v4.5.0, so it cannot be fixed at
    source) carries a spaced em dash and `e.g.` Latin abbreviations that
    trip that lint — but only in this destination; the env-file/wizard
    paths are plain text Vale never lints."""

    def test_em_dash_before_a_conjunction_splits_into_two_sentences(self):
        text = g._clean_help_for_markdown_table(
            "so tokens survive a restart — but rotating that secret "
            "invalidates every issued token."
        )
        assert " — " not in text
        assert "restart. Rotating" in text

    def test_em_dash_without_a_known_conjunction_joins_with_a_semicolon(self):
        text = g._clean_help_for_markdown_table(
            "unset — it then backs every namespace, not just HTTP resumability."
        )
        assert " — " not in text
        assert "unset; it then backs" in text

    def test_eg_clause_becomes_a_parenthetical(self):
        """Deliberately not 'for example,': that phrasing satisfies
        Google.Latin but trips ai-tells.FormalTransitions for this shape of
        sentence — verified against the live Vale ruleset during
        development, not merely assumed."""
        text = g._clean_help_for_markdown_table(
            "Public base URL of the deployed server, e.g. "
            "`https://mcp.example.com`. Required for OIDC."
        )
        assert "e.g." not in text
        assert "(`https://mcp.example.com`)" in text

    def test_eg_clause_terminator_lookahead_does_not_stop_at_a_url_dot(self):
        """A URL's own periods (`mcp.example.com`) must not be mistaken for
        the sentence-ending period that closes the `e.g.` clause."""
        text = g._clean_help_for_markdown_table(
            "OIDC discovery document URL, e.g. "
            "`https://auth.example.com/.well-known/openid-configuration`."
        )
        assert "e.g." not in text
        assert "(`https://auth.example.com/.well-known/openid-configuration`)." in text

    def test_ie_becomes_that_is(self):
        text = g._clean_help_for_markdown_table("Uses an alias, i.e. a friendly name.")
        assert "i.e." not in text
        assert "that is, a friendly name." in text

    def test_text_without_any_of_the_patterns_is_unchanged(self):
        text = "Plain help text with no special punctuation."
        assert g._clean_help_for_markdown_table(text) == text


class TestMarkdownVocabularyNormalisation:
    """Vale's spell-check is driven by `.vale/styles/config/vocabularies/
    Base/accept.txt`, which is `_skip_if_exists` — an existing downstream
    keeps its own copy forever, so a term added there reaches only fresh
    renders. The generated table text, by contrast, arrives on every
    `copier update`. Vocabulary therefore has to be normalised on the
    generator side, the only lever that propagates."""

    def test_jwts_does_not_reach_a_spliced_docs_table(self, fake_project):
        """End to end through `write_artifacts`, because the vocabulary is
        presentation context the caller supplies — a bare `render_md_table`
        call has none in scope, so testing that way would prove nothing about
        what actually ships."""
        answers = g.load_answers(fake_project)
        vars_ = g.collect_vars(fake_project, answers)
        var = next(v for v in vars_ if v.suffix == "OIDC_JWT_SIGNING_KEY")
        assert "JWTs" in var.help  # sanity: core's text has it

        g.write_artifacts(fake_project, check=False)
        for rel in ("docs/guides/authentication.md", "docs/deployment/oidc.md"):
            text = (fake_project / rel).read_text(encoding="utf-8")
            assert var.name in text  # sanity: the var reached this page
            assert "JWTs" not in text, rel
            assert "JSON Web Tokens" in text, rel
